### ISSUE TITLE
Uncaught Errors from async calls to Firebase

### ISSUE THREAD

**Issue by CarsonHerness** [CEHAT-Clinic/dashboard#241]
Chrome Dev Tools is showing "Uncaught exception" for async calls to Firebase in the front-end code, even though the errors are caught and being handled. This is likely related to how promises are handled, but it is not clear why the current implementation is not working. It could be because the error is being thrown in another call stack, per [this documentation](https://catchjs.com/Docs/AsyncAwait).

Converting the async/await in try/catch statements to then/catch statements seems to fix the issue.

**Comment by acgrobman** [comment]
Is this the thing you fixed in recent PR #544?

**Comment by CarsonHerness** [comment]
Yes but I didn't check the entire front end for try/catch statements so I will re-check and close during bug fix
