### ISSUE TITLE
Use new PurpleAir API

### ISSUE THREAD

**Issue by CarsonHerness** [CEHAT-Clinic/dashboard#398]
From PurpleAir:

> NOTICE: PurpleAir is migrating all users to our new API at https://api.purpleair.com. Please email contact@purpleair.com to get a key to use it and you should know that we will be preventing access to the current url’s at www.purpleair.com/data.json and www.purpleair.com/json soon.

[Doc from PurpleAir](https://docs.google.com/document/d/15ijz94dXJ-YAZLi9iZ_RaBwrZ4KtYeCy08goGBwnbCU/edit) with more information.

We currently use https://www.purpleair.com/json in the `getThingspeakKeysFromPurpleAir` function in `functions/src/aqi-calculation/util.ts`.

**Comment by CarsonHerness** [comment]
From email from PurpleAir that included our API key:

> The data from individual sensors will update no less than every 30 seconds. As a courtesy, we ask that you limit the number of requests to no more than once every 1 to 10 minutes, assuming you are only using the API to obtain data from sensors. If retrieving data from multiple sensors at once, please send a single request rather than individual requests in succession.

**Comment by CarsonHerness** [comment]
I added the READ API Key to GitHub secrets and the "Amber's Env" file in Drive as `REACT_APP_PURPLEAIR_READ_API_KEY`

**Comment by acgrobman** [comment]
Closed by #444
