### ISSUE TITLE
Add loading component to map

### ISSUE THREAD

**Issue by CarsonHerness** [CEHAT-Clinic/dashboard#458]
The map takes a long time to render, so if we can show a loading component until the map is ready, this will improve our website's "functionality score" from Lighthouse

**Comment by CarsonHerness** [comment]
the slow load time might also be hurting our page ranking for Google

**Comment by akampen** [comment]
Closing because not implementing. I looked into this and it seems like the map component does render instantaneously, but the map and its markers take time to render (on Here's end), so there's nothing we can do to fix it.
