### ISSUE TITLE
Add sensor name to downloaded sensor data function

### ISSUE THREAD

**Issue by CarsonHerness** [CEHAT-Clinic/dashboard#460]

**Comment by acgrobman** [comment]
Is this handled by #537?

**Comment by CarsonHerness** [comment]
Mostly, I'll close it once I add that info to the backend function that I'll use to download all data in the old format

**Comment by acgrobman** [comment]
It appears @akampen made a new bug #553 for that or am I misunderstanding

**Comment by CarsonHerness** [comment]
You are correct, this issue can be closed
