### ISSUE TITLE
Make Home page return more readable

### ISSUE THREAD

**Issue by akampen** [CEHAT-Clinic/dashboard#487]
Use subcomponents or something else to make this easier to read. Our first attempt to do so resulted in significant re-rendering, which is why we merged the code anyway.

**Comment by akampen** [comment]
Comments from initial PR:

I got a little lost in the ternary operators and the &&, so would it be possible to create some subcomponents for some of the JSX chunks? I have an example of subcomponents in the ManageSensors file, and the subcomponents I think would be MobileMap or MobileGauge.

I think it might be easier to read too if there were one isMobile ternary operator that had all of the mobile versions of each component rather than 3 isMobile checks for the 3 different subcomponents of the home page

**Comment by CarsonHerness** [comment]
Closing issue as wontfix
