### ISSUE TITLE
Check translations on mobile screen (collapsable UI components)

### ISSUE THREAD

**Issue by akampen** [CEHAT-Clinic/dashboard#495]
Hillary, I wanted to build code off of this code so I just merged without the review. If you get a chance look these over and I can edit them. Thanks!

**Comment by hillaryrguez** [comment]
public/locales/es/home.json

2 sitio web instead of sitio de web

6 para ver más información sobre el sensor elegido

9 sensor elegido

11 Cambiar el Mapa de Sensores

12 Cambiar el Indicador AQI

13 Cambiar el Gráfico del AQI
