### ISSUE TITLE
Errors in console for the map when resizing the console.

### ISSUE THREAD

**Issue by akampen** [CEHAT-Clinic/dashboard#604]

**Comment by akampen** [comment]
@CarsonHerness I just spent over an hour working on this with no luck. Unless someone else has time to help, I will not address this issue before code freeze. Should we close the issue or leave it open (since technically it's still an issue)

**Comment by CarsonHerness** [comment]
Maybe let's mark it as "will not fix" on Thursday?

**Comment by CarsonHerness** [comment]
Closing issue as wontfix
